In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import sys

import numpy as np
import pandas as pd

In [4]:
module_path = os.path.abspath("../")
sys.path.append(module_path) #add parent directory to path to detect the modules

In [5]:
STORE_ENV = 'DATA_STORE_PATH'
os.environ[STORE_ENV] = './tmp/nhl' #set data store path as environment variable

#creating the data store folder if doesn't exist [Otherwise it fails]
if not os.path.isdir(os.environ[STORE_ENV]):
     os.makedirs(path)

### Data Acquisition

In [6]:
from ift6758.data import NHL

In [22]:
path = os.environ.get(STORE_ENV) #get store path from environment variable 
#nhl = NHL(2019, path = path) # for just one year
nhl = NHL(2015, 2018, path = path) # for more than one season eg. 2019 to 2020 (inclusive)

#data = nhl.get_data(game_types = ['02'])
#data = nhl.get_data(reload = True) #To force reload the files from cache or download

#### Convert to Dataframe

In [23]:
#print("No. of games: ", len(data))
event_types = ['SHOT', 'GOAL'] #relevant type of events.
#df = nhl.to_DataFrame(event_types) #creates dataframe only after all the data is loaded to memory
df = nhl.to_DataFrame_optimized(event_types, game_types = ['02']) #creates dataframe by loading data on-the-go 1 season at a time to memory.

Loading 2015-2016 regular season data...
Load success!
Processing games...

100%|█████████████████████████████████████| 1230/1230 [00:00<00:00, 1612.02it/s]

Loading 2016-2017 regular season data...
Load success!
Processing games...

100%|█████████████████████████████████████| 1230/1230 [00:01<00:00, 1174.53it/s]

Loading 2017-2018 regular season data...
Load success!
Processing games...

100%|█████████████████████████████████████| 1271/1271 [00:01<00:00, 1160.34it/s]

Loading 2018-2019 regular season data...
Load success!
Processing games...

100%|█████████████████████████████████████| 1271/1271 [00:00<00:00, 1618.11it/s]

In [24]:
#playground
df.head()
#df[(df['event_type'] == 'GOAL') & (df['empty_net'] == True)]

,season,game_id,game_type,date_time,period,period_time,event_type,team,team_code,rink_side,...,shooter,goalie,shot_type,empty_net,strength,prev_event_type,prev_coord_x,prev_coord_y,prev_period,prev_period_time
0,2015-2016,2015020001,R,2015-10-07T23:24:23Z,1,00:51,SHOT,Toronto Maple Leafs,TOR,right,...,Brad Boyes,Carey Price,Wrist Shot,None,None,HIT,94.0,-34.0,1,00:40
1,2015-2016,2015020001,R,2015-10-07T23:24:38Z,1,01:05,SHOT,Toronto Maple Leafs,TOR,right,...,Nazem Kadri,Carey Price,Snap Shot,None,None,GIVEAWAY,-37.0,-28.0,1,00:58
2,2015-2016,2015020001,R,2015-10-07T23:27:21Z,1,01:06,SHOT,Toronto Maple Leafs,TOR,right,...,Nazem Kadri,Carey Price,Snap Shot,None,None,SHOT,-79.0,0.0,1,01:05
3,2015-2016,2015020001,R,2015-10-07T23:25:24Z,1,01:53,SHOT,Toronto Maple Leafs,TOR,right,...,Daniel Winnik,Carey Price,Wrist Shot,None,None,HIT,-91.0,35.0,1,01:35
4,2015-2016,2015020001,R,2015-10-07T23:27:08Z,1,02:37,SHOT,Toronto Maple Leafs,TOR,right,...,Joffrey Lupul,Carey Price,Tip-In,None,None,FACEOFF,-69.0,-22.0,1,02:32

### Data Clean

In [25]:
from ift6758.data import clean_data

 **Before**

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311086 entries, 0 to 311085
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   season            311086 non-null  object
 1   game_id           311086 non-null  int64
 2   game_type         311086 non-null  object
 3   date_time         311086 non-null  object
 4   period            311086 non-null  int64
 5   period_time       311086 non-null  object
 6   event_type        311086 non-null  object
 7   team              311086 non-null  object
 8   team_code         311086 non-null  object
 9   rink_side         311086 non-null  object
 10  coord_x           311086 non-null  float64
 11  coord_y           311086 non-null  float64
 12  shooter           311086 non-null  object
 13  goalie            310810 non-null  object
 14  shot_type         311053 non-null  object
 15  empty_net         28287 non-null   object
 16  strength          29176 non-null   object
 17  prev_event_type   311086 non-null  object
 18  prev_coord_x      306133 non-null  float64
 19  prev_coord_y      306133 non-null  float64
 20  prev_period       311086 non-null  int64
 21  prev_period_time  311086 non-null  object
dtypes: float64(4), int64(3), object(15)
memory usage: 52.2+ MB

**After**

In [27]:
c_df = clean_data(df)
c_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311086 entries, 0 to 311085
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   season            311086 non-null  object
 1   game_id           311086 non-null  int64
 2   game_type         311086 non-null  object
 3   date_time         311086 non-null  object
 4   period            311086 non-null  int64
 5   period_time       311086 non-null  object
 6   event_type        311086 non-null  object
 7   team              311086 non-null  object
 8   team_code         311086 non-null  object
 9   rink_side         311086 non-null  object
 10  coord_x           311086 non-null  float64
 11  coord_y           311086 non-null  float64
 12  shooter           311086 non-null  object
 13  goalie            310810 non-null  object
 14  shot_type         311086 non-null  object
 15  empty_net         311086 non-null  object
 16  strength          311086 non-null  object
 17  prev_event_type   311086 non-null  object
 18  prev_coord_x      306133 non-null  float64
 19  prev_coord_y      306133 non-null  float64
 20  prev_period       311086 non-null  int64
 21  prev_period_time  311086 non-null  object
dtypes: float64(4), int64(3), object(15)
memory usage: 52.2+ MB

In [28]:
c_df.head()

,season,game_id,game_type,date_time,period,period_time,event_type,team,team_code,rink_side,...,shooter,goalie,shot_type,empty_net,strength,prev_event_type,prev_coord_x,prev_coord_y,prev_period,prev_period_time
0,2015-2016,2015020001,R,2015-10-07T23:24:23Z,1,00:51,SHOT,Toronto Maple Leafs,TOR,right,...,Brad Boyes,Carey Price,Wrist Shot,False,Even,HIT,94.0,-34.0,1,00:40
1,2015-2016,2015020001,R,2015-10-07T23:24:38Z,1,01:05,SHOT,Toronto Maple Leafs,TOR,right,...,Nazem Kadri,Carey Price,Snap Shot,False,Even,GIVEAWAY,-37.0,-28.0,1,00:58
2,2015-2016,2015020001,R,2015-10-07T23:27:21Z,1,01:06,SHOT,Toronto Maple Leafs,TOR,right,...,Nazem Kadri,Carey Price,Snap Shot,False,Even,SHOT,-79.0,0.0,1,01:05
3,2015-2016,2015020001,R,2015-10-07T23:25:24Z,1,01:53,SHOT,Toronto Maple Leafs,TOR,right,...,Daniel Winnik,Carey Price,Wrist Shot,False,Even,HIT,-91.0,35.0,1,01:35
4,2015-2016,2015020001,R,2015-10-07T23:27:08Z,1,02:37,SHOT,Toronto Maple Leafs,TOR,right,...,Joffrey Lupul,Carey Price,Tip-In,False,Even,FACEOFF,-69.0,-22.0,1,02:32

### Feature Design

In [29]:
from ift6758.feature import extract_features, transform_features

In [30]:
r_df = extract_features(c_df)
r_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311086 entries, 0 to 311085
Data columns (total 30 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   date_time                 311086 non-null  object
 1   season                    311086 non-null  object
 2   game_id                   311086 non-null  int64
 3   game_type                 311086 non-null  object
 4   game_seconds              311086 non-null  int64
 5   period                    311086 non-null  int64
 6   period_time               311086 non-null  object
 7   period_seconds            311086 non-null  int64
 8   event_type                311086 non-null  object
 9   coord_x                   311086 non-null  float64
 10  coord_y                   311086 non-null  float64
 11  prev_period_time          311086 non-null  object
 12  prev_event_type           311086 non-null  object
 13  prev_coord_x              306133 non-null  float64
 14  prev_coord_y              306133 non-null  float64
 15  team                      311086 non-null  object
 16  team_code                 311086 non-null  object
 17  goal_side                 311086 non-null  object
 18  shooter                   311086 non-null  object
 19  goalie                    310810 non-null  object
 20  shot_distance             311086 non-null  float64
 21  shot_angle                311085 non-null  float64
 22  distance_from_prev_event  306133 non-null  float64
 23  time_from_prev_event      311086 non-null  int64
 24  rebound                   311086 non-null  bool
 25  change_in_angle           311081 non-null  float64
 26  speed                     306112 non-null  float64
 27  shot_type                 311086 non-null  object
 28  empty_net                 311086 non-null  object
 29  strength                  311086 non-null  object
dtypes: bool(1), float64(9), int64(5), object(15)
memory usage: 69.1+ MB

In [31]:
r_df[['goal_side','coord_x', 'coord_y', 'shot_distance', 'shot_angle']]

       goal_side  coord_x  coord_y  shot_distance  shot_angle
0           left    -55.0      6.0          34.53      -10.01
1           left    -79.0      0.0          10.00       -0.00
2           left    -75.0     -1.0          14.04        4.09
3           left    -55.0    -36.0          49.52       46.64
4           left    -61.0     -1.0          28.02        2.05
...          ...      ...      ...            ...         ...
311081     right     67.0    -19.0          29.07      -40.82
311082      left    -78.0      1.0          11.05       -5.19
311083      left    -82.0     10.0          12.21      -55.01
311084      left    -81.0      1.0           8.06       -7.13
311085     right     74.0      4.0          15.52       14.93

[311086 rows x 5 columns]

In [32]:
r_df.to_csv(f'{path}/nhl_data_clean.csv')

In [33]:
m_df = transform_features(r_df)
m_df.head()

,date_time,season,game_id,game_type,game_seconds,period,period_time,period_seconds,event_type,coord_x,...,shot_distance,shot_angle,distance_from_prev_event,time_from_prev_event,rebound,change_in_angle,speed,shot_type,empty_net,strength
0,2015-10-07T23:24:23Z,2015-2016,2015020001,R,51,1,00:51,51,0,-55.0,...,34.53,10.01,154.28,11,0,0.00,14.03,7,0,Even
1,2015-10-07T23:24:38Z,2015-2016,2015020001,R,65,1,01:05,65,0,-79.0,...,10.00,0.00,50.48,7,0,0.00,7.21,4,0,Even
2,2015-10-07T23:27:21Z,2015-2016,2015020001,R,66,1,01:06,66,0,-75.0,...,14.04,4.09,4.12,1,1,4.09,4.12,4,0,Even
3,2015-10-07T23:25:24Z,2015-2016,2015020001,R,113,1,01:53,113,0,-55.0,...,49.52,46.64,79.61,18,0,0.00,4.42,7,0,Even
4,2015-10-07T23:27:08Z,2015-2016,2015020001,R,157,1,02:37,157,0,-61.0,...,28.02,2.05,22.47,5,0,0.00,4.49,5,0,Even